source "http://rubygems.org"

# Specify your gem's dependencies in partystreusel.gemspec
gemspec path: '..'

group :assets do
  gem 'coffee-script'
end

group :development, :test do
  gem 'actionpack', '~> 3.2'
  gem 'railties',   '~> 3.2'
  gem 'sass-rails', "~> 3.2"
  gem 'tzinfo'

  gem 'thin'

  gem 'jasminerice'
  gem 'jquery-rails'
  gem 'i18n-js'
  gem 'guard-jasmine', '1.19.2'
end
